# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d4f168cedf7f1dbe1b2ccc61fc95fdab8929b6008adeac3bbc278a6e73c886ca072342a1d2ae5fdb88a451f96d4a986fc171e39bca6d28d7e1403bb37def025

test:
  secret_key_base: d383ef4f7617948d3b422f2e5275c1e196802b08bd2de5acb412c574bfd3165445c61c7d4e99d83eb723f56114653f9bb5d3e5efcb61de8be4d10332887552df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
