# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6772262ddc778363e11fae2b97bfb02b62b3992b24f1e6e8d4c4c3d0aae14da85aa8733f2b3e2b26cc231f8a3cbf9ada451e224c88fecfc8da2bc179b67318d

test:
  secret_key_base: 10ed8798cb5bab22ae2b9f5804deda6eafa7f35a560469f6a5c4dbe212dc7cb544ccdb4620892891b5f5501eb7a41893103a9ee30d760088565468a0dac58867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
